name: NISAR_Biomass
channels:
  - conda-forge
dependencies:
  - rasterio
  - numpy
  - matplotlib
  - gdal
  - scipy
  - pandas
  - scikit-learn
  - ipywidgets
  - h5py
  - earthaccess
  - pyproj
  - geopandas
  - asf_search 
  - fpdf
  - tqdm
  - boto3
  - jupyter
  - ipykernel
  - notebook
  - nb_conda_kernels  
  - pre-commit  
  - plotly
  - seaborn
